### ISSUE TITLE
[Bug] 备注太长会导致事件管理器界面下事件宽度显示异常

### ISSUE THREAD

**Issue by yeqingyu0305** [Moyf/yearly-glance#39]
### Bug Description | 问题描述

在事件管理器界面，如果一个事件的【事件备注】文字内容较多的话，那么宽度也会随之变大。

### Expected Behavior | 预期行为
事件宽度应该受到限制

### Actual Behavior | 实际行为
备注写多长，宽度就会变成多大，回车也不行

### Screenshots | 截图

![Image](https://github.com/user-attachments/assets/80924de7-de3d-45e3-8471-d1d15bb8de8f)
![Image](https://github.com/user-attachments/assets/8f38be5a-e2f4-4952-8888-ac9ca050303c)

**Comment by Moyf** [comment]
```css
:is(.yg-event-manager-container .event-manager-content) .event-remark {
  max-width: 280px;
}
```

本地先应用这个 CSS 片段临时修一下，回头我们更新上去。

> CSS 样式的用法：https://forum-zh.obsidian.md/t/topic/43995
